CuteWebserv/webserv

src/Config/Config.cpp, src/main.cpp
file path 경로 수정 했습니다!!
변경된 내용이 적어 형식 없이 올리겠습니다!
=> fix: file path 경로 수정

include/Parser.hpp, include/Request.hpp, include/RequestPool.hpp, include/StatusCode.hpp, include/ValidationStatus.hpp, src/Parser/Parser.cpp, src/Parser/main.cpp
- 팀 코드 컨벤션에 맞추어 기존 코드를 수정하였습니다. 
- `Request`, `RequestPool` 구조체에 Canonical Form 을 추가했습니다.
- 위의 구조체들은 클래스에 준하기 때문에 별도의 `.hpp` 파일로 분리했습니다.
- 함수 내에서 작업 단위를 구분하기 위해 개행을 추가했습니다.
- 변수나 함수 내부 작동과 관련한 주석을 추가했습니다.
- #22
=> Style/modify code convention#22

Makefile, include/HttpProcessor.hpp, include/MethodHandler.hpp, include/Response.hpp, include/ResponseGenerator.hpp, src/Response/Response.cpp
=> fix: create a response class and fix some of Makefile

include/Server.hpp, src/Server/Server.cpp, src/utils/ft_split.cpp
Issue Number: #31 
- server.hpp  에 cgi_process_end, time_out_event ENUM을 추가하였습니다!
- 각 이벤트는 다음과 같은 역할을 합니다
- CGI_PROCESS_END
- CGI프로세스가 정상적인 종료를함
- wait()
- timer 이벤트 삭제
- pipe의 내용을 읽어 메시지 만들기
- write 이벤트 등록
- CGI_PROCESS_TIMEOUT
- CGI 프로세스가 비정상적으로 오래 작동함
- kill()
- wait()
- PROCESS_END 이벤트 삭제
- PIPE close()
- write 이벤트 등록
=> feat: cgi 이벤트 처리 인터페이스 구현 #31

Makefile, include/Parser.hpp, include/RequestPool.hpp, include/Server.hpp, server.conf, src/Parser/Parser.cpp, src/Server/Server.cpp, src/Server/bind.cpp, src/Server/listen.cpp, src/Server/setServers.cpp, src/Server/socket.cpp
Issue Number: 55
멀티 port 및 다중 서버 블록을 받을 수 있도록 코드를 수정 하였습니다!
=> feat : multi port multi server_block 적용 #55

default.config
Configuration file의 기본 Directives 관련 사항을 반영한 example 파일을 워킹 디렉토리 루트에 default.conf로 저장해 공유합니다.
관련 Directives 및 configuration file에 유효한 입력 값들을
#62  번 이슈에 관련 사항을 상세히 기록했습니다.
=> doc : add default.conf for example #62

.vscode/settings.json, include/MethodHandler.hpp, src/HttpProcessor/MethodHandler.cpp, src/ResponseGenerator/ResponseGenerator.cpp, src/temp/beforeHttpProcessor.cpp
class를 새로 생성하지 않고, MethodHandler에서만 사용하는 기능이기 때문에, 관련 기능을 위한 멤버함수들을 private멤버함수로 추가하였습니다.
Issue Number: #65 
Response구조체의 auto_index플래그가 동작하도록 수정하였고, GET메소드에서만 동작하도록 하였습니다.
=> feat: MethodHandler member functions about autoindex #65

.vscode/settings.json, include/CgiHandler.hpp, src/CgiHandler/CgiHandler.cpp, src/CgiHandler/main.cpp
CgiHandler에서 시스템 함수 에러 발생 시, 아무 행동도 하지 않음
Issue Number: #71
pipe, fork, execve 등 시스템 함수에서 에러 발생 시,
예외 처리로 에러 메시지를 출력하도록 하는 try-catch문 삽입
=> Feat/cgi handler try catch#71

Makefile, include/Config.hpp, include/Log.hpp, include/Server.hpp, src/Config/Config.cpp, src/Config/content.cpp, src/Log/Log.cpp, src/Server/Server.cpp, src/Server/socket/bind.cpp, src/Server/socket/kqueue.cpp, src/Server/socket/listen.cpp, src/Server/socket/setServers.cpp, src/Server/socket/socket.cpp, src/main.cpp, src/utils/ft_error.cpp
Issue Number: #79 
- `Log` 클래스에서 `printf` 함수와 비슷한 출력문을 종류 별로 생성했습니다.
- `INFO` : 일반적인 정보를 표시하기 위해 사용
- `ERROR` : 에러가 발생한 경우 출력하기 사용
- `DEBUG` : 디버깅 목적으로 값을 출력하기 위해 사용
출력문 예시는 아래와 같습니다.
- 서버 시작 시 아스키 아트를 출력하도록 추가했습니다.
=> Feat/create log class#79

include/CgiHandler.hpp, src/CgiHandler/CgiHandler.cpp, src/Config/print.cpp, src/HttpProcessor/HttpProcessor.cpp, src/HttpProcessor/PathFinder.cpp, src/Parser/Parser.cpp, src/Server/Server.cpp, src/Server/event/error.cpp, src/Server/event/read.cpp, src/Server/event/timer.cpp, src/Server/event/write.cpp, src/utils/ft_split.cpp
디버깅 목적 또는 단순 출력문으로 `std::cout` 을 직접 사용했습니다.
Issue Number: #84 
- `Log` 클래스를 이용해서 출력하도록 변경했습니다.
- `CgiHandler` 클래스에서 `getDataFromCgi` 함수는 더 이상 필요하지 않아서 삭제했습니다. 
- kqueue 에서 non-blocking 방식으로 데이터를 읽도록 개선했습니다.
=> Feat/change cout to log#84

src/CgiHandler/CgiHandler.cpp, src/CgiHandler/get_python.py, src/CgiHandler/index.html, src/CgiHandler/post_python.py
CGI 파이썬 스크립트에서 텍스트, 바이너리 파일을 처리하는 각각의 코드는 있었으나,
입력값에 따라 분기하는 코드는 없었음.
Issue Number: #87 
GET : file 이름의 확장자를 비교해, 그에 따라 text 혹은 image 파일에 해당하는 헤더를 내보냄.
POST : 들어온 요청의 content_type을 비교해, 그에 따라 해당하는 헤더를 작성함.
=> feat: set if/else in cgi script #87

src/HttpProcessor/MethodHandler.cpp
GET요청시 문제가 있어서, if문의 구조를 바꿨습니다.
=> fix: GetMethodHandler::methodRun #88

src/CgiHandler/get_python.py, src/CgiHandler/post_python.py
문법 오류로 작동 안 함..
Issue Number: #91
else if 대신 elif
| 대신 or
로 문법을 고쳐 작동되게 함.
=> fix: python: else if -> elif, | -> or #91

server.conf, src/Config/content.cpp, src/HttpProcessor/HttpProcessor.cpp
들어온 request에 해당하는 method를 HttpProcessor에서 실행한다.
들어온 request에 해당하는 method 가 해당 location 블록에 accepted method 인지 확인하고 실행한다.
accepted가 아니라면 405 에러 페이지 반환
=> feat/add some for checking acceted method #107

src/HttpProcessor/HttpProcessor.cpp, src/ResponseGenerator/ResponseGenerator.cpp
response generator에서 cgi에서 error를 보낼 시 catch하는 구문 추가
=> fix: error catch # 109

data/upload/ab, data/upload/dd, data/upload/ddd, server.conf, src/HttpProcessor/HttpProcessor.cpp, src/HttpProcessor/MethodHandler.cpp, src/Parser/Parser.cpp, src/ResponseGenerator/ResponseGenerator.cpp, test_message
post method 작동시 존재하지 않는 경로가 들어올 경우, cute webserv 프로젝트의 워킹 디렉토리 가장 상위 폴더에 request 된 파일이 생성되었습니다.
POST, DELETE, PUT, HEAD 모두 존재하지 않는 경로의 요청이 들어올 경우, BAD_REQUEST error 페이지를 클라이언트에게 반환합니다.
=> Fix/make post delete put perfect #111

include/ValidationStatus.hpp, src/Parser/Parser.cpp
Issue Number: #117
- chunked body 전체 사이즈가 0 인 경우 오류가 발생하지 않도록 수정했습니다.
=> Fix/chunked body offset#117

src/HttpProcessor/MethodHandler.cpp
존재하지 않는 디렉토리에 autoindex가 생성되는 버그가 있었음
404 Not Found 오류페이지를 생성하도록 고침
=> fix: fix error when the directory is not exist #120

Makefile, include/Parser.hpp, include/RequestPool.hpp, src/Parser/Parser.cpp, src/Parser/parseBody.cpp, src/Parser/parseChunkedBody.cpp, src/Parser/parseFirstLine.cpp, src/Parser/parseHeaders.cpp, src/Server/event/read.cpp
Issue Number: #125 
- 기존에 작성했던 parser 에서 복잡한 로직을 정리하고 단순하게 정리했습니다.
=> Refac/parser cpp 리팩토링#125

server.conf, src/HttpProcessor/MethodHandler.cpp, src/HttpProcessor/PathFinder.cpp
경로에 /를 붙여서 요청을 보낼 시, 오토인덱스 페이지 오류 해결
오토인덱스가 인덱스 페이지보다 먼저 띄워주는 오류 해결
=> fix: /를 붙인 경로 시 오류 해결, autoindex우선 순위 해결 #126

data/put_test/tmp_file, joonhan.conf, log_file
=> fix some worng files

cgi_tester.conf, include/Config.hpp, src/Config/Config.cpp, src/Config/content.cpp
config 파일 유효성 검사 및 공백 추가
Issue Number: 155
=> feat: config 파일 유효성 검사 및 공백 추가 #155

error_page.conf, include/PathFinder.hpp, include/ResponseGenerator.hpp, src/HttpProcessor/PathFinder.cpp, src/ResponseGenerator/ResponseGenerator.cpp
=> Feat/create members about error page #158

cgi_tester.conf, data/cgi/hello.py, data/cgi/hi.pl, src/ResponseGenerator/ResponseGenerator.cpp
=> Feat/add perl file - multi cgi #167

cgi_tester.conf, data/cgi/post_test.py, data/post_test.html, src/Parser/Parser.cpp, src/Server/event/write.cpp
Issue Number: #170
- Python CGI POST 요청을 보냈을 때, 이미지를 저장하지 못하던 문제를 해결했습니다.
- HTML form 태그의 속성으로 `enctype=multipart/form-data` 를 추가해주어야 정상적으로 body 에 binary data 가 담겨져서 갑니다.
- Python CGI 처리 코드에서는 cgi 모듈을 사용하면 body 에 담긴 헤더와 binary data 를 분리합니다.
=> Feat/python cgi post#170

Makefile, default.config, include/PathFinder.hpp, include/Server.hpp, include/ServerFinder.hpp, servername.conf, src/Server/Server.cpp, src/Server/event/read.cpp, src/Server/socket/setServers.cpp, src/Server/socket/socket.cpp, src/ServerFinder/ServerFinder.cpp
=> server_name을 이용해 host:port에 매칭되는 서버 찾기 #177

include/Config.hpp, src/Config/content.cpp
Issue Number: #185 
- configuration 파일에서 `error_page` 에 해당하는 파일을 열어서 저장하는 로직을 `openErrorPage` 함수로 분리했습니다.
close #185
=> refactor: Add openErrorPage function #185

include/Log.hpp, src/Log/Log.cpp, src/Server/event/read.cpp
Issue Number: #187 
클라이언트의 요청 method, uri 과 응답 코드를 출력하는 기능을 추가했습니다.
```bash
GET   /123  404
GET   /images/bangle_with_note.jpg  200
```
- 응답 코드가 400번 이상인 경우 빨간색으로 출력됩니다.
- 400번 미만은 초록색으로 출력됩니다.
=> feat: Add printRequestResult function #187

.vscode/settings.json, include/CgiHandler.hpp, include/HttpProcessor.hpp, include/MethodHandler.hpp, include/PathFinder.hpp, include/Response.hpp, include/ResponseGenerator.hpp, include/Server.hpp, src/HttpProcessor/HttpProcessor.cpp, src/HttpProcessor/MethodHandler.cpp, src/HttpProcessor/PathFinder.cpp, src/ResponseGenerator/ResponseGenerator.cpp
ResponseGenerator에서  Response클래스를 분리 시켰습니다.
MethodHandler, ResponseGenerator 클래스를 리팩토링 하였습니다.
=> ResponseGenerator에서 Response클래스 분리, ResponseGenerator, MethodHandler 리팩토링

src/CgiHandler/PostCgiHandler.cpp
에러 발생 시 close()가 중복될 수 있었음
Issue Number: #195 
close() 함수 위치를 한 곳에 몰아서, 더블 close() 상황을 방지함
=> fix: change close() in executeCgi() #195

src/HttpProcessor/PathFinder.cpp
=> change some # 200

include/PathFinder.hpp, src/HttpProcessor/PathFinder.cpp
=> make it more better #200

default.conf, src/Parser/Server.cpp, src/Server/Server.cpp, src/Server/event/client.cpp, src/Server/event/pipe.cpp, src/Server/event/process.cpp, src/Server/event/server.cpp, src/Server/event/static_file.cpp, src/Server/socket/setServers.cpp, src/ServerFinder/ServerFinder.cpp
=> Add/new guard - 메모리 부족 상황시 new에 guard 추가, 서버 파인더 수정
